[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
reqwest = { version = "0.12.12", features = ["http2", "json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
