alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: pitter-patter-redis-load-test-se
      match:
        authority:
          exact: ""
        path:
          prefix: /
name: pitpat-server
region: nyc
services:
  - dockerfile_path: server/Dockerfile
    envs:
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
        value: EV[1:WPe8qqJrPFkmD0d5HrWsDbKo/wtpetWm:A0DDBvnrYxaQMOj5AcGM+1l+v/6LJvFYodmvJ4NkCHHorECf1lttwmZ1DbVi2fhuXwRKVdPAJL9D5sOze68wtskda+amOxHqfgrDlAmBvYhKuKV5vPVrrrigSt5Bn6+86J5cC0/mG7BilS+72a1ByKMDrOACdU+ducnBVIFJOg==]
      - key: HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: 0.0.0.0
    github:
      branch: main
      deploy_on_push: true
      repo: handlewithcarecollective/pitter-patter-redis-load-test
    http_port: 3000
    instance_count: 4
    instance_size_slug: apps-d-1vcpu-1gb
    name: pitter-patter-redis-load-test-se
    source_dir: server
workers:
  - dockerfile_path: client/Dockerfile
    envs:
      - key: NUM_LISTENERS
        scope: RUN_TIME
        value: "100"
      - key: NUM_POSTERS
        scope: RUN_TIME
        value: "100"
      - key: NUM_DOCS
        scope: RUN_TIME
        value: "10"
      - key: BASE_URL
        scope: RUN_AND_BUILD_TIME
        value: https://pitpat-server-or5bv.ondigitalocean.app
    github:
      branch: main
      deploy_on_push: true
      repo: handlewithcarecollective/pitter-patter-redis-load-test
    instance_count: 3
    instance_size_slug: apps-d-4vcpu-8gb
    name: pitter-patter-redis-load-test-cl
    source_dir: client
